name: npm-publish
on:
  push:
    branches:
      - master
      - '*/*'
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: latest
      #    registry-url: https://registry.npmjs.org
      - run: sudo chmod o+rw /var/run/docker.sock
      - run: npm run test-container
      - if: github.event_name == 'release'
        run: |
          npm run build-container
          npm run run-container
